### ISSUE TITLE
Readme file - env variable incorrect

### ISSUE THREAD

**Issue by KierenB** [mikebroberts/clubby#1]
"CLUBHOUSE-KEY environment variable" should read "CLUBHOUSE_KEY environment variable" (note the underscore)

edit: saw in the code that it was CLUBHOUSE-KEY, it's just that bash was rejecting that as invalid. Apologies for the confusion.

**Comment by mikebroberts** [comment]
Actually you were correct, thanks. While hyphens work underscores are the more canonical separator (and work using the environment library I'm using)
