### ISSUE TITLE
Clubhouse API V2

### ISSUE THREAD

**Issue by camilleacey** [mikebroberts/clubby#2]
Hi Mike, 
I just wanted to let you know that we've released [Clubhouse API V2](https://clubhouse.io/api/rest/v2/). While V1 will continue to be supported, V2 exposes endpoints for several new features such as Teams, Milestones, and Categories.

**Comment by mikebroberts** [comment]
Thanks Camille. I just made an update to the README to let people know this only uses the old version of the API. I haven't used the project myself for over a year, so it's unmaintained at this point.
